### ISSUE TITLE
observ/computed calles dependent observables immediatly

### ISSUE THREAD

**Issue by emilbayes** [Raynos/observ#11]
I was a bit surprised that `observ/computed` tries to get the value of each of it's dependent observables upon initiation. This is contrary to how `observ` values themselves work. Or am I misunderstanding something?

**Comment by Raynos** [comment]
With `observ` you give it the initial value.

With `observ/computed` you give it a list of observables and it reads the value.

The important invariant here is that any `observ` must ALWAYS have a current value. For `observ/computed` to work it must get it's initial value; it only asks for the initial value again when the upstream observables changed.

**Comment by emilbayes** [comment]
Alright, I must have misunderstood the part where `observ` differs from `observable`, but your answer makes sense. Thanks!
